### ISSUE TITLE
Error: Call to undefined function array_key_first() 

### ISSUE THREAD

**Issue by andreafonsot** [bjverde/cnpjrfb#14]
Pessoal, fiz as instalações conforme recomendações e tive um erro numa classe. Não conheço o código a fundo. Primeiro contato com ele.

Alguém pode me ajudar? Pois acho que só deu aqui. Só fiz o download e copiei os arquivos para o www. Não mexi em nada. Esse erro acontece quando clico em Empresas. Os outros (Sócios e CNEA) funcionam certinho.
![image](https://user-images.githubusercontent.com/62852493/121835085-b77d1f00-cca6-11eb-9a13-c6f756d69de1.png)

http://localhost/cnpjrfb/index.php?class=EmpresaForm

Esse o link do erro

**Comment by bjverde** [comment]
@andreafonsot vi a sua mensagem! amanha vou verificar se faltou comitar algo e talvez gerar uma nova versão. Vou te avisar aqui

**Comment by andreafonsot** [comment]
@bjverde  Valeuu

**Comment by andreafonsot** [comment]
@bjverde também vou deixar o outro erro que deu aqui:

Eu instalei os pacotes do Python conforme instruções, porém deu erro ao Gerar os Grafos, consoante print abaixo

http://localhost/cnpjrfb/index.php?class=GeraGrafoForm&method=gerarGrafo&cnpj=00000000000191&cnpj_cpf_socio=%2A%2A%2A022878%2A%2A&nome_socio=ANTONIO+MAURICIO+MAURANO&key=00000000000191
![image](https://user-images.githubusercontent.com/62852493/121892635-66dfe300-ccf3-11eb-83bb-1767093d19f9.png)

**Comment by bjverde** [comment]
@andreafonsot  testei agora a tela Empresas está funcionando corretamente, sem erros. O que fiz ?
* PHP 7.3 
* clone o projeto do zero 
* acessei no navegador a pasta www do projeto.
* testeis os 3 menus.

No teste que fiz estou usando a versão 1.2.0 (ultima versão). O número da versão aparece no rodapé da pagina ou titulo da aba.

![image](https://user-images.githubusercontent.com/1070062/121938804-a671f380-cd22-11eb-8d82-a80e2475b03c.png)

**Comment by andreafonsot** [comment]
@bjverde Atualizei meu PHP e deu certo!! os três estão funcionado. Somente o Grafo que não está indo. Será que preciso configurar algo a mais no PHP para ler o Python? Porque os pacotes estão instalados

**Comment by andreafonsot** [comment]
@bjverde  Vou colocar print aqui novamente:

![image](https://user-images.githubusercontent.com/62852493/121939692-a7575500-cd23-11eb-81de-e334f4e146b9.png)

**Comment by bjverde** [comment]
@andreafonsot sobre o Python melhorei a mensagem de erro para tentar debugar porém no seu caso a mensagem vai aparecer.

```bash
cd C:\wamp64\www\cnpjrfb\app\control\controllers\..\..\CNPJ-full\;python3 consulta.py cnpj 00000000000949 graficos/00000000000949 --nivel 3 --viz 2>&1
```
Terá que verficar:
1 - Se vc tem a pasta  `C:\wamp64\www\cnpjrfb\app\CNPJ-full\`  existe. Se não existir, terá executar a configuração do Python https://github.com/bjverde/cnpjrfb#parte-2---python
2 - Se dentro da pasta CNPJ-full conseque executar o comando `python3 consulta.py cnpj 00000000000949 graficos/00000000000949 --nivel 3 --viz 2>&1`
2.1 - o primeiro problema e mais provavel é falta do python3 instalado e configurado no path do windows

**Comment by bjverde** [comment]
@andreafonsot atualizado para a versão v1.2.1 a unica mudança foi a melhoria da mensagem de erro. Agora vai aparecar algo como

![image](https://user-images.githubusercontent.com/1070062/121941880-32d1e580-cd26-11eb-88f2-e30014413822.png)

**Comment by andreafonsot** [comment]
@bjverde realmente, aparece essa mensagem. mas eu instalei os pacotes do python, conforme orientado. Estou tentando ver o que está faltando.. mas estou com dificuldade. Podes me ajudar?

**Comment by andreafonsot** [comment]
![image](https://user-images.githubusercontent.com/62852493/121945812-93632180-cd2a-11eb-9725-b2041f416277.png)

![image](https://user-images.githubusercontent.com/62852493/121945834-98c06c00-cd2a-11eb-9786-5b07941bb583.png)
@bjverde

**Comment by andreafonsot** [comment]
@bjverde eu realmente não sei se tenho que configurar algo a mais no Python. Eu instalei os pacotes via pip. Mas parece que o servidor não localiza o python. Não sei.

Tentei tb o comando do banco de dados inteiro, mas diz que não encontra o python. Cabeça já está fervendo
Se puder me ajudar, eu ficaria mto grato.

**Comment by bjverde** [comment]
@andreafonsot execute apenas comando antes virgula  `cd C:\wamp64\www\cnpjrfb\app\control\controllers\..\..\CNPJ-full\;` esse comando vai apenas entrar na pasta CNPJ-full e coloque o resultado. 

Se não existir, terá executar a configuração do Python https://github.com/bjverde/cnpjrfb#parte-2---python mais precisamente o item 2. 

**2 Copie o projeto [CNPJ-FULL](https://github.com/fabioserpa/CNPJ-full) e coloque na pasta <caminho servidor>/cnjrfb/app/CNPJ-full**


Se conseguir acessar a pasta CNPJ-Full. Dentro da pasta CNPJ-full execute o comando `python3 consulta.py cnpj 00000000000949 graficos/00000000000949 --nivel 3 --viz 2>&1` e coloque o resultado

**Comment by andreafonsot** [comment]
@bjverde você diz essa tela?
![image](https://user-images.githubusercontent.com/62852493/121951800-c5c44d00-cd31-11eb-8884-bd2f256ea4e3.png)

**Comment by andreafonsot** [comment]
@bjverde a segunda linha:

![image](https://user-images.githubusercontent.com/62852493/121951964-fefcbd00-cd31-11eb-86b4-b5c7baaa756e.png)

**Comment by bjverde** [comment]
@andreafonsot vc não tem o python3 totalmente configurado. Vou pesquisar como fazer isso no windows.

**Comment by andreafonsot** [comment]
@bjverde mas eu acessei pelo terminal CMD o python e instalei os pacotes, até desinstalei e reinstalei a última versão do python. O que mais precisa ser feito? Valeuuu muito pela sua ajuda! Quero mto usar esse sistema de consulta

**Comment by bjverde** [comment]
@andreafonsot quando fui fazer a instalação do Python reparei um detalhe importante. Precisa marcar a opção "add Python 3.9 to PATH" que vem desmarcada por padrão. 

![image](https://user-images.githubusercontent.com/1070062/121952840-2607be80-cd33-11eb-95a2-e4e8caf27ea3.png)

fonte do instalador: https://www.python.org/downloads/

**Comment by bjverde** [comment]
@andreafonsot  na etapa 3 é interessante marcar "Install for all users". **NÃO** é obrigatório 

![image](https://user-images.githubusercontent.com/1070062/121953443-f1483700-cd33-11eb-9f4c-e5262a04516b.png)

**Comment by andreafonsot** [comment]
@bjverde eu marquei essa opção. Até reinstalei mais uma vez para ter certeza. Mas continua aparecendo a mesma tela no terminal

Microsoft Windows [versão 10.0.19041.1052]
(c) Microsoft Corporation. Todos os direitos reservados.

C:\Users\Meu Note>cd C:\wamp64\www\cnpjrfb\app\control\controllers\..\..\CNPJ-full\

C:\wamp64\www\cnpjrfb\app\CNPJ-full>python3 consulta.py cnpj 00000000000191 graficos/00000000000191 --nivel 3 --viz 2>&1
Python nÒo encontrado; execute sem argumentos para instalar na Microsoft Store ou desabilite este atalho a partir de Configuraþ§es > Gerenciar Aliases de ExecuþÒo do Aplicativo.

C:\wamp64\www\cnpjrfb\app\CNPJ-full>

**Comment by bjverde** [comment]
@andreafonsot estou com o mesmo problema !! Estou vendo como resolver essa a primeira vez que estou instalando no windows. Até hoje todas as instalações foram no Linux. Me da mais um tempo

**Comment by andreafonsot** [comment]
@bjverde Beleza!! Pelo menos não é só aqui. :S

**Comment by bjverde** [comment]
@andreafonsot não tenho boas noticias !! Vai demorar para colocar para funcionar no windows 10 a geração do GRAFO. o problema todo é forma como o PHP executa comando externos no windows. **A consulta básica funciona**

Eu cheguei em um pontos que se pegar os comandos e executar no terminal vai funcionar para gerar o grafo. Porém devida a falta de permissões no Apache ou PHP não é possível rodar o comando, fora alguns problemas relacionados ao ambiente do Python. 

Diante disso usar o Docker no Windows é uma solução que contorna todos esses problemas de ambiente e instalação. Só que não vou mentir inicialmente o Docker pode ser complicado.

Tudo que falei está na versão 1.2.2

**Comment by bjverde** [comment]
Quando tenta rodar o grafo no windows vai aparecer a mensagem. É só copiar e colocar o comando em um terminal e depois clicar no link mais abaixo

![image](https://user-images.githubusercontent.com/1070062/121974764-7c3a2900-cd56-11eb-922e-41344f9ff659.png)

**Comment by andreafonsot** [comment]
@bjverde Eu vou tentar fuçar então como se usa Docker! Nunca tinha ouvido falar.

Mas segui suas instruções e gerei o gráfico pelo link:
![image](https://user-images.githubusercontent.com/62852493/121976538-721a2980-cd5a-11eb-94bd-1af2789eb8fe.png)

Muito obrigado pela sua atenção e prontidão!! Vou acompanhar o projeto para as novas atualizações
Abração

**Comment by bjverde** [comment]
@andreafonsot agora vem uma etapa que é bem demorada mesmo !!  Tudo que fez até aqui foi preparar o ambiente para a leitura do banco de dados completo.  [Parte 3 - O banco completo !](https://github.com/bjverde/cnpjrfb#parte-3---o-banco-completo-) vai tomar um bom tempo processando os dados a receita

**Comment by andreafonsot** [comment]
@bjverde vou tentar fazer agora!! Eu vou executar direto pelo CMD!! Eu havia baixado tudo os dados do CNPJ mas apaguei quanto deletei a versão 1.2.1 kk esqueci desse detalhe. Estou baixando de novo agora. Você acha que conseguirei fazer via CMD:

https://github.com/fabioserpa/CNPJ-full#dados-p%C3%BAblicos-cnpj---convers%C3%A3o-para-csvsqlite-e-consultas

Eu li ali, primeiro tenho que colocar tudo numa pasta e converter para sqlite

**Comment by bjverde** [comment]
@andreafonsot bom saber que até etapa 2 funcionou !! Vou fechar essa isseu.

Para quem está lendo o problema da etapa lendo continua https://github.com/bjverde/cnpjrfb/issues/15
