### ISSUE TITLE
sqlite3.OperationalError: nu such table: main.empresas Conversão para Sqlite

### ISSUE THREAD

**Issue by andreafonsot** [bjverde/cnpjrfb#15]
Boa noite @bjverde 

Estou na parte 3 da instalação:

Eu coloquei todos os arquivos dentro de uma pasta que criei chamada download.

Depois executei o comando :  C:\wamp64\www\cnpjrfb\app\CNPJ-full>   python cnpj.py "download" sqlite "data" --dir

Obs. Tinha um arquivo dentro da pasta "data" do CNPJ_full.db com 56kb que tinha dado erro na criação dos indices.

Aí eu apaguei e comecei de novo, aí deu erro esse diferente, que agora não faço ideia do porque:

![image](https://user-images.githubusercontent.com/62852493/121989297-473bcf80-cd72-11eb-967b-04ef18d1c217.png)

**Comment by andreafonsot** [comment]
O arquivo gerado ficou com 0 kb.. achei que já tinha sido descompactado pelo código, mas parece que erro foi no caminho mesmo.

![image](https://user-images.githubusercontent.com/62852493/121989530-ab5e9380-cd72-11eb-925d-2a75cdbe5fb0.png)

**Comment by andreafonsot** [comment]
Vou fazer uma tentativa diferente: Copiei o arquivo que estava no data (56 KB) de volta. E executei o comando com --noindex para ver se funciona... só não sei se isso poderá prejudicar de alguma forma depois

**Comment by andreafonsot** [comment]
![image](https://user-images.githubusercontent.com/62852493/121990913-fda0b400-cd74-11eb-95bf-6a2de0c35adc.png)

Total de registros está vindo zerado por que?? @bjverde SOS

**Comment by bjverde** [comment]
@andreafonsot hoje estou apertado !! amanhã acredito que será mais tranquilo para te ajudar.

Adiantando alguns pontos:
* sim vc vai conseguir toda parte 3 em linha de comando.
* recomendo fazer um backup temporario dos arquivos da receita só para não precisar baixar novamente
* vou testar a geração da base de dados com o primeiro arquivo

**Comment by andreafonsot** [comment]
@bjverde Sem problemas!! Somente com tua ajuda tenho conseguido avançar!

Eu fiz um backup agora!! Fiz minhas tentativas ali pelas linhas de comando.. vou dxar vc tentar tb p ver se o resultado é o mesmo

**Comment by andreafonsot** [comment]
@bjverde Corrido por ai? Só passando p dar um Up mesmo!! Abcss

**Comment by andreafonsot** [comment]
@bjverde Help! haha

**Comment by bjverde** [comment]
@andreafonsot não esqueci de vc apenas estou mega atarefado vou tentar fazer no FDS

**Comment by bjverde** [comment]
@andreafonsot qual é o tamanho dos arquivos ZIP da receita que vc tem ?? Tem dois dias que estou tentando baixar os arquivos e aparece a mensagem

```
Serviço temporariamente indisponível.
Tente novamente em alguns instantes. 
```

https://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/dados-publicos-cnpj

**Comment by andreafonsot** [comment]
Oi, @bjverde Esse link que vc está tentando é o antigo. O novo agora é https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/cadastros/consultas/dados-publicos-cnpj

Quantos aos arquivos, tem ao todo 4,54gb (são 30 arquivos)

![image](https://user-images.githubusercontent.com/62852493/123519789-baebaf80-d683-11eb-9367-f9688fe24abc.png)

**Comment by andreafonsot** [comment]
@bjverde será que compensa eu tentar instalar uma máquina virtual do Linux para rodar? vc usa o Linux aí né? o problema tem sido com o Windows

**Comment by bjverde** [comment]
@urusaki2021 valeu pela dica link coloquei para baixar !! Mais tartes faço alguns teste.

Sobre usar Linux, eu acho mais interessante por vários motivos !! Porém com o Windows 10 você pode usar uma solução meio termo que pode ser bem interessante para o tipo de problema. A solução seria usar Docker com WSL (Subsistema do Windows para Linux) no Win10, depois de tudo configura será quase como um sistema instalado no windows. 

Vatagens
* vai rodar exatamente a mesma versão de toda arquitetura envolvida em todos os computadores
* já tem um arquivo de configuração pronto para isso

Desvantagem
* mais uma coisa para aprender instalar e usar
* pode ter uma cruva chata de aprendizagem um pouco chata


Se desejar usar instale o WSL 2
https://docs.microsoft.com/pt-br/windows/wsl/install-win10

Depois é só instalar o docker 
https://docs.docker.com/docker-for-windows/install/

**Comment by bjverde** [comment]
Relacionado com #23 
Isseu FECHADA, devido as alterações do Layout de dados da receita federal !
Será feito uma nova versão do sistemas.
