### ISSUE TITLE
Performance pessima com o banco de dados completos

### ISSUE THREAD

**Issue by ruevers** [bjverde/cnpjrfb#17]
Com o banco de dados completos o sistema fica muito, mas muito lento, como dba me disponho a ajudar os desenvolvedores a melhorar isso, vou fazer uns testes com mysql, o que deve resolver o problema, pois geralmente é sql porcaria que vem do framework, mas me disponho a ajudar a  melhorar no lite, o que ficaria inviavel e demoraria muito pra solucionar eu tendo que estudar e aprender um framework novo, seria mais fácil eu fazer em laravel que já domino. Mas como gostei do projeto e visual, gostaria de ajudar nessa parte, pois estaria reinventado a roda refazendo tudo em laravel.

**Comment by bjverde** [comment]
@ruevers seja bem vindo ao projeto !! 

Confesso que nunca teste com o banco completo, porém eu sei que a falta de indicies pode prejudicar muito o tempo de resposta.  Na documentação do  [CNPJ-full do fabioserpa](https://github.com/fabioserpa/CNPJ-full) ele faz o alerta

```
O argumento opcional --noindex, aplicável somente para saída sqlite, indica que não devem ser gerados índices automaticamente. A criação de índices é muito recomendada e essencial para a funcionalidade de consultas.
```

**Comment by bjverde** [comment]
@ruevers pensando bem !! Talvez a sua ajuda seja melhora aproveitada no projeto original do [CNPJ-full do fabioserpa](https://github.com/fabioserpa/CNPJ-full) é o projeto dele que monta todo o banco de dados. No caso meu projeto apenas faz um interface visual para facilitar. 

A baixo uma lista dos fork do projeto do Fabio, tem um fork com foco em colocar pesquisas usando Elastic e tem outro fork com implementação no PostGresql
https://github.com/fabioserpa/CNPJ-full/network

**Comment by ruevers** [comment]
> @ruevers seja bem vindo ao projeto !!
> 
> Confesso que nunca teste com o banco completo, porém eu sei que a falta de indicies pode prejudicar muito o tempo de resposta. Na documentação do [CNPJ-full do fabioserpa](https://github.com/fabioserpa/CNPJ-full) ele faz o alerta
> 
> ```
> O argumento opcional --noindex, aplicável somente para saída sqlite, indica que não devem ser gerados índices automaticamente. A criação de índices é muito recomendada e essencial para a funcionalidade de consultas.
> ```

Sei que pode parecer arrogancia, mas tenho muito tempo de experiencia como dba e ultimamente vejo que a culpa de performance geralmente é codigo ruim e frameworks ruim, e instalando e testando no mysql, pude ver isso....pois toda vez que o framework monta as paginas, ele faz select count(*) nas tabelas, se usasse um campo ou (1) teria menos impacto, alem do mais usa like no cnpj, tentei mudar varios likes no forms, mas continua fazendo, infelizmente não achei o lugar, parece tambem ser interno do framework, esse like %cnpj% faz full scan no mysql e no sqlite tambem, então se um dia tentar usar a base toda, vai ver que seu aplicativo não vai funcionar ou demorar demais, apesar de ser uma otima ideia. Eu acredito e posso provar que  o problema é o framework e não o cnpj_full, que cria os indices modestos, mas no phyton dele as pesquisas rodam rapido e tambem servem para o basico de uma aplicação.

**Comment by ruevers** [comment]
> @ruevers pensando bem !! Talvez a sua ajuda seja melhora aproveitada no projeto original do [CNPJ-full do fabioserpa](https://github.com/fabioserpa/CNPJ-full) é o projeto dele que monta todo o banco de dados. No caso meu projeto apenas faz um interface visual para facilitar.
> 
> A baixo uma lista dos fork do projeto do Fabio, tem um fork com foco em colocar pesquisas usando Elastic e tem outro fork com implementação no PostGresql
> https://github.com/fabioserpa/CNPJ-full/network

Em postgress, mysql ou sqlite vai ser impossivel de usar, so serviria em oracle, pois tem como evitar as queries ruins que o framework faz. Algumas delas.
pessimo isso 
| cnpj | Query   | 11   | executing | SELECT count(*) FROM socios 
e isso tambem.
Query   | 18   | executing | SELECT cnpj, matriz_filial, razao_social, nome_fantasia, situacao, data_situacao, motivo_situacao, nm_cidade_exterior, cod_pais, nome_pais, cod_nat_juridica, data_inicio_ativ, cnae_fiscal, tipo_logradouro, logradouro, numero, complemento, bairro, cep, uf, cod_municipio, municipio, ddd_1, telefone_1, ddd_2, telefone_2, ddd_fax, num_fax, email, qualif_resp, capital_social, porte, opc_simples, data_opc_simples, data_exc_simples, opc_mei, sit_especial, data_sit_especial FROM empresas WHERE (cnpj like '%57.620.247/0001-28%') ORDER BY cnpj asc LIMIT 10 |


isso porque dei um jeito no banco mysql e uma melhorada, no sqlite não tem como fica impossivel usar com toda base.

**Comment by ruevers** [comment]
Consegui melhorar pagina de socios e cnae tirando os likes dos forms, mas esse select das paginas de empresa não...
Query   | 18   | executing | SELECT cnpj, matriz_filial, razao_social, nome_fantasia, situacao, data_situacao, motivo_situacao, nm_cidade_exterior, cod_pais, nome_pais, cod_nat_juridica, data_inicio_ativ, cnae_fiscal, tipo_logradouro, logradouro, numero, complemento, bairro, cep, uf, cod_municipio, municipio, ddd_1, telefone_1, ddd_2, telefone_2, ddd_fax, num_fax, email, qualif_resp, capital_social, porte, opc_simples, data_opc_simples, data_exc_simples, opc_mei, sit_especial, data_sit_especial FROM empresas WHERE (cnpj like '%57.620.247/0001-28%') ORDER BY cnpj asc LIMIT 10 |

parece ser interno do framework, que digamos de passagem é bem bonito, mas pra performance é ruim se faz isso internamente.Não aguenta aplicações de grande porte igual laravel.
Resumindo, não tem nada de errado com o CNPJ_FULL e sim com o framework, vc conhecendo mais talvez possa corrigir, senão acho que vou partir pra laravel, espero ter contribuido e estou a disposição se precisar de ajuda.

**Comment by bjverde** [comment]
@ruevers interesante vou dar uma olhada na sua sugestão. Agora estou um pouco atarefado vou olhar com mais calma no fds

**Comment by ruevers** [comment]
> @ruevers interesante vou dar uma olhada na sua sugestão. Agora estou um pouco atarefado vou olhar com mais calma no fds

Resolvi o problema no mysql, como eu havia dito era a porcaria do framework, que apesar de ser bonito, um select full em todas as tabelas, e tambem mudei os likes, talvez volte os likes pra ajudar nas pesquisas, vou ver se o mesmo serve pra sqlite. em postgress acho que daria pra resolver no banco, resumindo, tirar os likes e mudar as coisas mal feitas no framwork. Ficou instantaneo, com a base completa apos correção.

**Comment by andreafonsot** [comment]
@ruevers no ambiente WIndows não consegui executar a parte 3 do código.. sabes por que??

**Comment by ruevers** [comment]
> @ruevers no ambiente WIndows não consegui executar a parte 3 do código.. sabes por que??

Ai fica dificil né amigo, nem colocou o erro....eu não tenho bola de cristal e tem outra o problema não tem nada haver com esse, então deveria ter aberto um issue novo. Está parecendo usuario que liga pro suporte e diz...meu computador não funciona mas não diz qual o problema..kkkk

**Comment by andreafonsot** [comment]
@ruevers tá amargurado ein.. já estamos discutindo isso em outra issue, apenas estava perguntando caso vc estivesse usando o windows,.. deixa quieto.. sucesso aí

**Comment by bjverde** [comment]
Amiguinhos, papai do céu falou "que nos amÁssemos, não que nos amassemos!"

@urusaki2021 me parece que vc é relativamente novo nesse mundo de busca de solução de bugs. Pode parece estranho mas o @ruevers fez nem foi grosso contigo, ele apenas te avisou que realmente está faltando contexto para conseguir te ajudar. 

para ter uma ideia o StackOverFlow que é o maior forúm de debates sobre TI na internet tem um guia de sobrevivem que é um pouco longo porém explica muito coisa. O link abaixo irá te mostrar

https://pt.meta.stackoverflow.com/questions/8045/guia-de-sobreviv%c3%aancia-do-stack-overflow-em-portugu%c3%aas

**Comment by bjverde** [comment]
Relacionado com #23
Isseu FECHADA, devido as alterações do Layout de dados da receita federal !
Será feito uma nova versão do sistemas.
