### ISSUE TITLE
mascara pra cnpj

### ISSUE THREAD

**Issue by ruevers** [bjverde/cnpjrfb#18]
Pesquisas de cnpj não retornam valor nenhm, falta colocar a mascara

     $formDinCnpjField = new TFormDinCnpjField('cnpj',$cnpjLabel);
        $cnpj = $formDinCnpjField->getAdiantiObj();
        $cnpj->setMask('99.999.999/9999-99',true); <------------AQUI

Na de socios e cnae é so adicionar essa linha e funciona, na de empresas não soube como fazer, continua lento e ruim.

**Comment by ruevers** [comment]
Correção para cnpj de empresa
$cnpjLabel = 'CNPJ';
        $formDinCnpjField = new TFormDinCnpjField('cnpj',$cnpjLabel,false,true);
        $cnpj = $formDinCnpjField->getAdiantiObj();
        $cnpj->setMask('99.999.999/9999-99',true);

        $listSituacaoCadastral = SituacaoCadastralEmpresa::getList();

        $frm->addFields([new Tlabel($cnpjLabel)],[$cnpj]);

**Comment by ruevers** [comment]
Abri um request com exemplo de empresa pois corrigi.
https://github.com/bjverde/cnpjrfb/pull/20
 e o 
https://github.com/bjverde/cnpjrfb/pull/19
para melhora de performace, ainda ruim, mas usavel.

**Comment by bjverde** [comment]
@ruevers obrigado mesmo pelas sugestões e correções ! Fiz o merge request e alterei a tela um pouco

![image](https://user-images.githubusercontent.com/1070062/124015235-d4119a80-d9ba-11eb-96e7-ea79c9ba20ea.png)

**Comment by bjverde** [comment]
Relacionado com #23
Isseu FECHADA, devido as alterações do Layout de dados da receita federal !
Será feito uma nova versão do sistemas.
