### ISSUE TITLE
Joins errados

### ISSUE THREAD

**Issue by ruevers** [bjverde/cnpjrfb#21]
Os Joins entre empresa e socios estão com algum problema, se pega um cnpj ou nome de empresa nao tras os socios e se pega o nome de socio com varias empresas não pega todas, não consegui identificar no codigo pois não conheço muito bem o framework, mas se usar a base toda, vai perceber varias incosistencias desse tipo.

**Comment by bjverde** [comment]
Relacionado com #23
Isseu FECHADA, devido as alterações do Layout de dados da receita federal !
Será feito uma nova versão do sistemas.
