### ISSUE TITLE
eu nao consigo instalar o programa, preciso tanto pegar os cnpj da receita mensalmente

### ISSUE THREAD

**Issue by limase** [bjverde/cnpjrfb#30]

**Comment by bjverde** [comment]
@limase desculpe a demora !! Todo os sistema está passando por uma reestruturação. Já estou próximo de tornar publica a próxima versão. Porém criar o banco de dados vai dar muito muito trabalho.

"A RFB informa aos usuários das informações disponibilizadas sobre os dados cadastrais do CNPJ - DADOS ABERTOS, que a partir da divulgação do mês de março de 2021"
https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/cadastros/consultas/dados-publicos-cnpj

**Comment by bjverde** [comment]
@limase  vc pode fazer algumas consultas no Brasil.io

https://brasil.io/dataset/socios-brasil/socios/
