### ISSUE TITLE
Versão do Template + Gerar Planilhas

### ISSUE THREAD

**Issue by diegomustafamarino** [bjverde/cnpjrfb#36]
Salve @bjverde e todo pessoal que ajudou no projeto, primeiramente gostaria de agradecer o esforço de todos!
Depois de dias na raça para conseguir mandar os dados para o postgres (eu nem sabia o que tava fazendo), eu consegui finalmente abastecer a base de dados com os dados atualizados de 25/12, fiquei muito feliz! Me interessei pelo seu projeto e mais um momento de raça, consegui implementar o modelo de consulta.
Porém notei que a versão do Template Adianti Framework disponível no site já está em 7.4, e o código foi desenvolvido na 7.3.
Caso não vejam problema nisso, gostaria de saber se podem disponibilizar a 7.3 para download, ou atualizar o projeto para o template 7.4.
Também quero inserir uma função de leads, já que trabalho com comércio, gostaria de saber se é muito complicado, ou se é possível:
Após a aplicação dos filtros, gerar uma planilha do excel contendo:
|Nome da empresa| Telefone 1| Telefone 2| Telefone 3|
Eu sei que dá para extrair a planilha inteira, porém achei o cruzamento de dados no SQL muito mais rápido, leve e prático que no Excel.
Além disso, eu vi que a quantidade de dados está limitada a 1000 na interface, mas acredito que isso seja fácil de resolver mudando algum arquivo de configuração do processo.

To felizão que estou quase conseguindo o que quero! Muita gratidão a todos! Tamo junto!

**Comment by bjverde** [comment]
@Diglee147 que bom que gostou !!

**Versão do Adianti** 
Acredito que projeto vai rodar sem problemas sobe o Adianti Framework 7.4 sem problemas. Não lembro de nada que precise ser atualizado no projeto para funcionar na versão 7.4.0. Porém caso aconteça algum problema abaixo o link de um fork da versão 7.3.0
https://github.com/bjverde/adianti-fork-framework


**PostgreSQL e outros Bancos** 
Tem modelos para alguns banco
https://github.com/bjverde/cnpjrfb/tree/master/modelo_banco

**Comment by bjverde** [comment]
@Diglee147 ,

*Leads*

Sim é possível fazer, basicamente seria definir quais os campos dos critérios de pesquisa e quais campos devem aparecer no resultado. Além da tela precisa lembrar de criar os índices de pesquisa no campos.

**Comment by diegomustafamarino** [comment]
ok @bjverde , muito obrigado! Tamo junto !
