### ISSUE TITLE
Erro no grafo

### ISSUE THREAD

**Issue by TplMArcelo** [bjverde/cnpjrfb#4]
Não consigo gerar o grafo n sei se tem algum error de sintese.
file C:\xampp\htdocs\testemarcelo\cnpjrfb\app\control\forms\GeraGrafoForm.php
function debug
class FormDinHelper
type ::
Debug
O sistema n�o pode encontrar o caminho especificado.

**Comment by bjverde** [comment]
@TplMArcelo desculpe a demora da resposta !!

Esse erro acontece quando na [GeraGrafoController.class.php#L31](https://github.com/bjverde/cnpjrfb/blob/master/www/cnpjrfb/app/control/controllers/GeraGrafoController.class.php#L31) 

Confesso que  não rodei os grafos no windows. Vamos descobrir juntos como resolver o problema. Lembrando os grafos são gerarados via um comando Python.

Descomente as linhas 32 a 36 isso vai leberar o Debug.  A linha 32 é comando completo em python

**Comment by renatoos1** [comment]
@bjverde , conseguiram identificar como corrigir esse erro? Estou com o mesmo. Parece que ele não identifica aonde está a pasta do consulta.py pra executar o código.

**Comment by bjverde** [comment]
@TplMArcelo  e @renatoos1  fiz algumas correções e testes no Linux e no Docker está tudo fucnionado bem !! O problema todo está no Windows, especialmente no windows10.

Veja a explicação no link https://github.com/bjverde/cnpjrfb/issues/14#issuecomment-861075812
