### ISSUE TITLE
Não consigo Rodar os scripts da parte 2

### ISSUE THREAD

**Issue by GleisonSette** [bjverde/cnpjrfb#40]
Bom dia! Antes de explicar o meu problema... eu não sou programador e entendo apenas sobre a lógica de programação.

Segui todo o passo a passo fornecido... intalei o aplicativo, configurei conforme instrução e ele roda com a pequena base de dados que você já deixou pre instalada.

Parte 2 
Baixei todos os arquivos .zip e salvei no "C:\xampp\htdocs\dados_receita\output_files"
Descompactei e salvei em "C:\xampp\htdocs\dados_receita\output_files"
conforme instrução nod "readme.txt"

Já em "C:\xampp\htdocs\cargabd" abri o CMD e executei o "index.php"

Resultado do arquivo de erro_log:

[07-Jun-2022 02:12:14 Europe/Berlin] PHP Warning:  Undefined array key 22 in C:\xampp\htdocs\cargabd\dao\EstabelecimentoDAO.class.php on line 85

Esse erro apresenta na linha 64 até a 92 referente a esse codigo:

` public function insert( array $linhaArquivoCsv )
    {
        $values = array( $linhaArquivoCsv[0]
                        , $linhaArquivoCsv[1]
                        , $linhaArquivoCsv[2]
                        , $linhaArquivoCsv[3]
                        , $linhaArquivoCsv[4]
                        , $linhaArquivoCsv[5]
                        , ValidarHelper::validarData($linhaArquivoCsv[6])
                        , $linhaArquivoCsv[7]
                        , $linhaArquivoCsv[8]
                        , $linhaArquivoCsv[9]
                        , ValidarHelper::validarData($linhaArquivoCsv[10])
                        , $linhaArquivoCsv[11]
                        , $linhaArquivoCsv[12]
                        , $linhaArquivoCsv[13]
                        , $linhaArquivoCsv[14]
                        , $linhaArquivoCsv[15]
                        , $linhaArquivoCsv[16]
                        , $linhaArquivoCsv[17]
                        , $linhaArquivoCsv[18]
                        , $linhaArquivoCsv[19]
                        , $linhaArquivoCsv[20]
                        , $linhaArquivoCsv[21]
                        , $linhaArquivoCsv[22]
                        , $linhaArquivoCsv[23]
                        , $linhaArquivoCsv[24]
                        , $linhaArquivoCsv[25]
                        , $linhaArquivoCsv[26]
                        , $linhaArquivoCsv[27]
                        , $linhaArquivoCsv[28]
                        , $linhaArquivoCsv[29]
                        );`

Fiz alteração conforme tutoriais no google para:

`public function insert( array $linhaArquivoCsv )
    {
        $values = array( 

        cnpj_basico => $linhaArquivoCsv[0]
        ,cnpj_ordem => $linhaArquivoCsv[1]
        ,cnpj_dv => $linhaArquivoCsv[2]
        ,identificador_matriz_filial => $linhaArquivoCsv[3]
        ,nome_fantasia => $linhaArquivoCsv[4]
        ,situacao_cadastral => $linhaArquivoCsv[5]
        ,data_situacao_cadastral => ValidarHelper::validarData($linhaArquivoCsv[6])
        ,motivo_situacao_cadastral => $linhaArquivoCsv[7]
        ,nome_cidade_exterior => $linhaArquivoCsv[8]
        ,pais => $linhaArquivoCsv[9]
        ,data_inicio_atividade => ValidarHelper::validarData($linhaArquivoCsv[10])
        ,cnae_fiscal_principal => $linhaArquivoCsv[11]
        ,cnae_fiscal_secundaria => $linhaArquivoCsv[12]
        ,tipo_logradouro => $linhaArquivoCsv[13]
        ,logradouro => $linhaArquivoCsv[14]
        ,numero => $linhaArquivoCsv[15]
        ,complemento => $linhaArquivoCsv[16]
        ,bairro => $linhaArquivoCsv[17]
        ,cep => $linhaArquivoCsv[18]
        ,uf => $linhaArquivoCsv[19]
        ,municipio => $linhaArquivoCsv[20]
        ,ddd_1 => $linhaArquivoCsv[21]
        ,telefone_1 => $linhaArquivoCsv[22]
        ,ddd_2 => $linhaArquivoCsv[23]
        ,telefone_2 => $linhaArquivoCsv[24]
        ,ddd_fax => $linhaArquivoCsv[25]
        ,fax => $linhaArquivoCsv[26]
        ,correio_eletronico => $linhaArquivoCsv[27]
        ,situacao_especial => $linhaArquivoCsv[28]
        ,data_situacao_especial => $linhaArquivoCsv[29]

                       
         );
        $result = $this->executeSql($sql, $values);
        return true;
    }`

rodei novamente e apresentou o seguinte erro:

[07-Jun-2022 03:44:45 Europe/Berlin] PHP Fatal error:  Uncaught Error: Undefined constant "codigo" in C:\xampp\htdocs\cargabd\dao\CnaeDAO.class.php:29
Stack trace:
#0 C:\xampp\htdocs\cargabd\controllers\UploadCsv.class.php(30): CnaeDAO->insert(Array)
#1 C:\xampp\htdocs\cargabd\controllers\Cargabanco.class.php(122): UploadCsv->executar()
#2 C:\xampp\htdocs\cargabd\controllers\Cargabanco.class.php(152): Cargabanco->carregaDadosTabela(Object(CnaeDAO), 'C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\cargabd\controllers\Cargabanco.class.php(91): Cargabanco->carregaDadosTabelaDoArquivo(Object(CnaeDAO), 'CNAECSV')
#4 C:\xampp\htdocs\cargabd\controllers\Cargabanco.class.php(39): Cargabanco->carregaDados()
#5 C:\xampp\htdocs\cargabd\index.php(22): Cargabanco->executar()
#6 {main}
  thrown in C:\xampp\htdocs\cargabd\dao\CnaeDAO.class.php on line 29
[07-Jun-2022 10:25:29 Europe/Berlin] PHP Fatal error:  Uncaught Error: Undefined constant "codigo" in C:\xampp\htdocs\cargabd\dao\CnaeDAO.class.php:29
Stack trace:
#0 C:\xampp\htdocs\cargabd\controllers\UploadCsv.class.php(30): CnaeDAO->insert(Array)
#1 C:\xampp\htdocs\cargabd\controllers\Cargabanco.class.php(122): UploadCsv->executar()
#2 C:\xampp\htdocs\cargabd\controllers\Cargabanco.class.php(152): Cargabanco->carregaDadosTabela(Object(CnaeDAO), 'C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\cargabd\controllers\Cargabanco.class.php(91): Cargabanco->carregaDadosTabelaDoArquivo(Object(CnaeDAO), 'CNAECSV')
#4 C:\xampp\htdocs\cargabd\controllers\Cargabanco.class.php(39): Cargabanco->carregaDados()
#5 C:\xampp\htdocs\cargabd\index.php(22): Cargabanco->executar()
#6 {main}
  thrown in C:\xampp\htdocs\cargabd\dao\CnaeDAO.class.php on line 29

Não consigo prosseguir dessa parte e abastecer a base de dados mysql na XAMPP.

Desde já agradeço pela sua boa vontade de disponibilizar esse programa para nós.

**Comment by bjverde** [comment]
@GleisonSette desculpe a demora !! Agora é só para mandar um oi a noite dou uma olhada direito no seu problema

**Comment by GleisonSette** [comment]
Ok.. muito obrigado pela atenção! 

Vou falar o que já fiz desde que mandei a mensagem.

Acessei https://github.com/aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ
Consegui abastecer quase todo o banco de dados com exceção do arquivo estabelecimento conforme esse link: https://github.com/aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ/issues/21

Sobre o aplicativo que você disponibilizou usando o [Adianti FrameWork](https://www.adianti.com.br/framework) eu consegui rodar ele normal.

Então a minha nova pergunta: É possivel conectar ele a base de dados do postgree que já está quase toda pronta?

Mais uma vez, agradeço a atenção e sua dedicação por isso.

**Comment by bjverde** [comment]
@GleisonSette sim possível alterar o banco que vai conectar 

Basta alterar o arquivo
https://github.com/bjverde/cnpjrfb/blob/master/www/cnpjrfb/app/config/maindatabase.php

informado os parâmetro corretos, o valor do type = "pgsql"

```
host = "192.168.1.102"
port = ""
name = "samples"
user = "postgres"
pass = "postgres"
type = "pgsql"
prep = "1"
```
