### ISSUE TITLE
Erro de execução

### ISSUE THREAD

**Issue by renatoos1** [bjverde/cnpjrfb#5]
Parabéns pelo trabalho, o que dá muito mais vida ao esforço do Fábio Serpa.
Eu não sou desenvolvedor então, peço desculpas se a questão seja muito básica.
Eu acredito que tenha feito tudo correto, mas as consultas não funcionam e apresentam o erro da imagem.
Saberia me dizer, o que estou fazendo de errado?

Muito obrigado!
<img width="869" alt="erro" src="https://user-images.githubusercontent.com/60509389/109492342-9717b480-7a69-11eb-9680-268d2fa75c91.PNG">

**Comment by bjverde** [comment]
@renatoos1 obrigado por te gostado do projeto. Estou um pouco enrolado com a entrega de outro projeto, acredito que quarta consigo olhar mais atenção

**Comment by renatoos1** [comment]
@bjverde , muito obrigado pela rápida resposta e pela atenção!

**Comment by bjverde** [comment]
@renatoos1 não esqueci de você !! Comecei olhar o bug, já adianto que esse bug está ligado as telas mais avançadas para fazer consultas personalizadas para que conhece SQL. Para o usuário normal o impacto inicial é mínimo.

**Comment by renatoos1** [comment]
@bjverde tranquilo! Vá no seu tempo mesmo. Não sou técnico, então teria maior dificuldade mesmo.

**Comment by renatoos1** [comment]
> @bjverde tranquilo! Vá no seu tempo mesmo. Não sou técnico, então teria maior dificuldade mesmo.

Perfeito!
Acabei de testar e está funcionando perfeitamente.
Parabéns!
