### ISSUE TITLE
Dúvida sobre erro SQLSTATE[HY000] [14] unable to open database file

### ISSUE THREAD

**Issue by williambse** [bjverde/cnpjrfb#9]
Não consigo utilizar pois não carrega o banco de dados. Erro: SQLSTATE[HY000] [14] unable to open database file

SO: Windows 10 Pro
PHP: 7.3
Python: 3.9.5

No sistema, tem como eu baixar todas as empresas de uma cidade que estão ativa ?

**Comment by bjverde** [comment]
@williambse  desculpe a demora estou envolvido com muito projetos e não tive tempo olhar o seu problema.

a mensagem  `Erro: SQLSTATE[HY000] [14] unable to open database file` reflete basicamente um erro no caminho do arquivo do banco de dados

**Comment by bjverde** [comment]
@williambse  problema resolvido !!! 

* baixe a versão 1.2.0 agora 
* siga as instruções https://github.com/bjverde/cnpjrfb/blob/master/README.md
* agora é possível pesquisar por municipio
